# This line can actually be removed
parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true

env:
  node: true
  browser: true

extends:
  - airbnb-typescript/base
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended

rules:
  react/react-in-jsx-scope: off
